name: shared_prefs_resource
description: Deprecated. Please use `async_resource_flutter` instead. An AsyncResource interface for Flutter shared preferences storage.
version: 0.0.2+1
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/shared_prefs_resource

dependencies:
  flutter:
    sdk: flutter
  async_resource: ^0.1.2
  shared_preferences: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=1.19.0 <3.0.0"